### ISSUE TITLE
Implement teacher sign up links generation

### ISSUE THREAD

**Issue by auduchinok** [hwproj/hwproj#14]
Think about a way it should work. Should you call some method form Rails console to get a link? Maybe add some button to an existing teachers?
How a teacher will get it? Should it be sent via email? Or even allow them sign up but disable account before they're verified?

Generate sign up token and store it in the database.

Good tokens tutorial:
https://www.railstutorial.org/book/account_activation

**Comment by jzuken** [comment]
I guess that's already done?

**Comment by auduchinok** [comment]
Yep, looks like @Soulflayer1337 didn't mention the issue in his commit.
